function [textData] = ReadAxographfiles(fileToRead1)
%IMPORTFILE(FILETOREAD1)
% %  Imports data from the specified file
% %  FILETOREAD1:  file to read
% 
% %  Auto-generated by MATLAB on 18-Feb-2023 15:38:48
% 
% % DELIMITER = '\t';
% % HEADERLINES = 1964;
% 
% % Import the file
% rawData1 = importdata(fileToRead1);
% 
% % For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% % return a simple array.  If so, generate a structure so that the output
% % matches that from the Import Wizard.
% [~,name] = fileparts(fileToRead1);
% textData= rawData1;


fid = fopen(fileToRead1, 'r');
C = textscan(fid, '%s', 'Delimiter', '\\', 'HeaderLines', 1);
textData= C{1,1};
fclose(fid);